// svelte/src/components/App.svelte
<script>
  import { fetchSong } from '../api';
  import { ws, wsID, sendLoadSetlist, sendLoadSong, sendDisplaySection, sendClearBeamer, sendChangeKey, wsConfig } from '../websocket';

  import LeftSidebar from './LeftSidebar.svelte'
  import Center from './Center.svelte'
  import RightSidebar from './RightSidebar.svelte'

  const getIsMobile = () => window.innerWidth < window.innerHeight;

  let beamerViewComponent;
  let leftSidebarComponent;
  let centerComponent;
  let rightSidebarComponent;

  let isMobile = getIsMobile();
  let leftVisible = true;
  const toggleLeft = () => leftVisible = !leftVisible;
  const showLeft = () => leftVisible = true;
  const hideLeft = () => leftVisible = false;
  let rightVisible = false;
  const toggleRight = () => rightVisible = !rightVisible;
  const showRight = () => rightVisible = true;
  const hideRight = () => rightVisible = false;
  let mode = 'musican'; // musican, singer, beamer-control, beamer

  let currentSong;
  let currentCapo = 0;
  let currentKey = 'Self';
  let fontScale = 0.8;

  const onClickCenter = (event) => {
    if (event.y > window.innerHeight*3/4) {
      leftSidebarComponent.nextSong();
    } else if (event.y < window.innerHeight/4) {
      leftSidebarComponent.prevSong();
    } else if (event.x < window.innerWidth/2) {
      toggleLeft();
    } else if (event.x > window.innerWidth/2) {
      toggleRight();
    }
  };
  const onSongSelect = async (item, isRemote) => {
    if (!isRemote) {
      sendLoadSong(item.title, item.key);
      sendClearBeamer();
    }
    if (isMobile) {
      hideLeft();
    }
    if (!item.key || item.key === 'Self') {
      item.key = currentKey;
    }
    centerComponent.clearBeamer();
    currentSong = await fetchSong(item.title, manipulateKey(item.key, -currentCapo));
  };
  const onSetlistSelect = async (title, isRemote) => {
    if (!isRemote) {
      sendLoadSetlist(title);
    }
  };
  const onModeChange = (m) => {
    mode = m;
    if (isMobile) {
      hideRight();
    }
    if (mode === 'beamer') {
      hideLeft();
      hideRight();
    }
  };
  const onSectionSelect = (idx, isRemote) => {
    if (idx === null) {
      if (!isRemote) {
        sendClearBeamer()
      }
      centerComponent.clearBeamer();
      return;
    }
    if (!isRemote) {
      sendDisplaySection(currentSong.title, idx)
    }
    centerComponent.displayBeamer(idx);
  };
  const keys = ['A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab'];
  const manipulateKey = (key, offset) => {
    if (offset === 0) {
      return key;
    }
    if (key === 'Self') {
      return `${key}:${(offset + 12) % 12}`;
    }
    if (offset < 0)  {
      offset += 12;
    }
    return keys[(keys.indexOf(key)+offset) % 12];
  }
  const onKeyChange = (key, isRemote) => {
    if (currentKey == 'Self') {
      currentKey = 'Ab';
    }
    if ( key == '+1' ) {
      key = manipulateKey(currentKey, 1);
    } else if (key == '-1') {
      key = manipulateKey(currentKey, -1);
    }
    currentKey = key;
    if (!isRemote) {
      sendChangeKey(currentKey);
    }
    onSongSelect({title: currentSong.title, key: currentKey}, true);
  }
  const onCapoChange = (capo) => {
    if (currentSong.key.indexOf(':') > -1 ) {
      currentSong.key = 'Self';
    } else {
      currentSong.key = manipulateKey(currentSong.key, currentCapo);
    }
    if (capo === 1) {
      currentCapo = (currentCapo + 1) % 12;
    } else if (capo === -1) {
      currentCapo = (currentCapo + 11) % 12;
    } else if (capo === 0) {
      currentCapo = 0;
    }
    onSongSelect({title: currentSong.title, key: currentSong.key}, true);
  }
  const onFontScaleChange = (update) => {
    if (update === 'reset') {
      fontScale = 0.8;
    } else if (update === 'increment') {
      fontScale = Math.round((fontScale + 0.05 + Number.EPSILON) * 100) / 100;
    } else if (update === 'decrement') {
      fontScale = Math.round((fontScale - 0.05 + Number.EPSILON) * 100) / 100;
    }
  };

  ws.addEventListener("message", (event) => {
    if (!wsConfig.receiveControls) {
      return;
    }
    const msg = JSON.parse(event.data);
    if (msg.senderID === wsID) {
      return;
    }
    if (msg.type === "load setlist") {
      onSetlistSelect(msg.title, true);
    } else if (msg.type === "load song") {
      onSongSelect({title: msg.title, key: msg.key}, true);
      leftSidebarComponent.selectTitle(msg.title);
    } else if (msg.type === "display section") {
      onSectionSelect(msg.idx, true);
    } else if (msg.type === "clear beamer") {
      centerComponent.clearBeamer();
    } else if (msg.type === "change key") {
      onKeyChange(msg.key, true);
    }
  });

  document.onkeydown = (e) => {
    if (e.key === " " || e.key === "j" || e.keyCode === 40) {
      leftSidebarComponent.nextSong();
    } else if (e.key === "k" || e.keyCode === 38) {
      leftSidebarComponent.prevSong();
    } else if (
      e.key === "A" ||
      e.key === "B" ||
      e.key === "C" ||
      e.key === "D" ||
      e.key === "E" ||
      e.key === "F" ||
      e.key === "G" ||
      e.key === "b" ||
      e.key === "#" ||
      e.key === "r"
    ) {
      let key = e.key === "r" ? "Self" : e.key;
      if (key === "b" || key === "#") {
        if (currentKey === 'Self') {
          return;
        }
        key = `${currentKey.substring(0, 1)}${key}`;
      }
      onKeyChange(key);
    } else if (e.key === "1") {
      onModeChange('musican');
    } else if (e.key === "2") {
      onModeChange('singer');
    } else if (e.key === "3") {
      onModeChange('beamer-control');
    } else if (e.key === "4") {
      onModeChange('beamer');
    } else if (e.keyCode === 37) {
      toggleLeft();
    } else if (e.keyCode === 39) {
      toggleRight();
    } else if (e.key === '+') {
      onFontScaleChange('increment');
    } else if (e.key === '-') {
      onFontScaleChange('decrement');
    } else if (e.key === '=') {
      onFontScaleChange('reset');
    } else if (e.key === 'c') {
      onCapoChange(1);
    } else if (e.key === 'x') {
      onCapoChange(-1);
    } else if (e.key === 'v') {
      onCapoChange(0);
    }
  };

  window.onresize = () => isMobile = getIsMobile();
</script>

<style>
  #app {
    position: fixed;
    height: 100%;
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: flex-start;
    align-items: stretch;
  }
</style>

<main>
  <div id='app'>
    <LeftSidebar
      onSongSelect={onSongSelect}
      onSetlistSelect={onSetlistSelect}
      visible={leftVisible}
      bind:this={leftSidebarComponent}
      />
    <Center
      onClickCenter={onClickCenter}
      onSectionSelect={onSectionSelect}
      mode={mode}
      currentSong={currentSong}
      fontScale={fontScale}
      visible={!isMobile || (!leftVisible && !rightVisible)}
      bind:this={centerComponent}
      />
    <RightSidebar
      onModeChange={onModeChange}
      onKeyChange={onKeyChange}
      onCapoChange={onCapoChange}
      currentKey={currentKey}
      currentCapo={currentCapo}
      fontScale={fontScale}
      mode={mode}
      wsID={wsID}
      wsConfig={wsConfig}
      visible={rightVisible}
      bind:this={rightSidebarComponent}
    />
  </div>
</main>

// react/src/components/App.jsx
import React from "react";

import { Grid, CssBaseline } from "@material-ui/core";
import { MuiThemeProvider, createMuiTheme } from "@material-ui/core/styles";

import { fetchTitles, fetchSong } from "../api";
import {
  ws,
  sendLoadSong,
  sendDisplaySection,
  sendClearBeamer,
} from "../websocket";

import TitleList from "./TitleList";
import SongView from "./SongView";
import SectionSelector from "./SectionSelector";
import Beamer from "./Beamer";

const appTheme = createMuiTheme({
  palette: {
    type: "dark",
  },
});

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title_idx: 0,
      section_idx: null,
      titles: [],
      song: null,
      key: null,
      display: "SongView",
      window: {
        width: 0,
        height: 0,
      },
      show_song_selector: false,
    };

    this.updateWindowDimensions = this.updateWindowDimensions.bind(this);

    ws.addEventListener("message", (event) => {
      const msg = JSON.parse(event.data);
      if (msg.type === "load song") {
        this.loadSong(msg.title, null, msg.key);
        this.displaySection(null);
      } else if (msg.type === "display section") {
        this.displaySection(msg.idx);
      } else if (msg.type === "clear beamer") {
        this.displaySection(null);
      }
    });

    document.onkeydown = (e) => {
      if (e.key === " " || e.key === "j") {
        this.nextSong();
      } else if (e.key === "k") {
        this.prevSong();
      } else if (
        e.key === "A" ||
        e.key === "B" ||
        e.key === "C" ||
        e.key === "D" ||
        e.key === "E" ||
        e.key === "F" ||
        e.key === "G" ||
        e.key === "b" ||
        e.key === "#" ||
        e.key === "r"
      ) {
        const key = e.key === "r" ? null : e.key;
        this.setKey(key);
      } else if (e.key === "1") {
        this.setDisplay("SongView");
      } else if (e.key === "2") {
        this.setDisplay("SectionSelector");
      } else if (e.key === "3") {
        this.setDisplay("Beamer");
      } else if (e.key === "T") {
        this.toggleSongSelector();
      }
    };
  }

  toggleSongSelector() {
    this.setState(() => ({
      show_song_selector: !this.state.show_song_selector,
    }));
  }

  updateWindowDimensions() {
    this.setState(() => ({
      window: {
        width: window.innerWidth,
        height: window.innerHeight,
      }
    }));
  }

  displaySection(section_idx) {
    this.setState(() => ({
      section_idx: section_idx,
    }));
  }

  setDisplay(display) {
    this.setState(() => ({
      display: display,
    }));
  }

  setKey(key) {
    if (key === "b" || key === "#") {
      if (this.state.key === null) {
        return;
      }
      key = `${this.state.key.substring(0, 1)}${key}`;
    }
    sendLoadSong(this.state.song.title, key);
  }

  async componentDidMount() {
    const titles = await fetchTitles();
    const song = await fetchSong(titles[0]);
    this.setState(() => ({
      title_idx: 0,
      titles: titles,
      song: song,
    }));
    this.updateWindowDimensions();
    window.addEventListener('resize', this.updateWindowDimensions);
  }

  nextSong() {
    if (this.state.title_idx >= this.state.titles.length - 1) {
      return;
    }
    sendLoadSong(this.state.titles[this.state.title_idx + 1]);
  }

  prevSong() {
    if (this.state.title_idx < 1) {
      return;
    }

    sendLoadSong(this.state.titles[this.state.title_idx - 1]);
  }

  async loadSong(title, idx, key) {
    idx = idx != null ? idx : this.state.titles.indexOf(title);
    title = title != null ? title : this.state.titles[idx];
    const song = await fetchSong(title, key);
    this.setState(() => ({
      title_idx: idx,
      song: song,
      key: key,
    }));
  }

  async loadTitles() {
    const titles = await fetchTitles();
    this.setState(() => ({
      titles: titles,
    }));
  }

  render() {
    return (
      <MuiThemeProvider theme={appTheme}>
        <CssBaseline />
        <div>
          {this.state.display !== "Beamer" && this.state.show_song_selector && (
            <Grid container>
              <Grid item style={{ width: "20vw", height: "100vh" }}>
                <TitleList
                  titles={this.state.titles}
                  idx={this.state.title_idx}
                  selectTitle={(title) => sendLoadSong(title, null)}
                />
              </Grid>
              <Grid item style={{ width: "80vw", height: "100vh" }}>
                {this.state.display === "SongView" && (
                  <SongView
                    song={this.state.song}
                    nextSong={this.nextSong.bind(this)}
                    prevSong={this.prevSong.bind(this)}
                    toggleSongSelector={this.toggleSongSelector.bind(this)}
                  />
                )}
                {this.state.display === "SectionSelector" && (
                  <SectionSelector
                    song={this.state.song}
                    selectSection={(idx) =>
                      sendDisplaySection(this.state.song.title, idx)
                    }
                    clearBeamer={sendClearBeamer}
                  />
                )}
              </Grid>
            </Grid>
          )}
          {this.state.display === "SongView" && ! this.state.show_song_selector && (
            <SongView
              song={this.state.song}
              nextSong={this.nextSong.bind(this)}
              prevSong={this.prevSong.bind(this)}
              toggleSongSelector={this.toggleSongSelector.bind(this)}
            />
          )}
          {this.state.display === "SectionSelector" && ! this.state.show_song_selector && (
            <SectionSelector
              song={this.state.song}
              selectSection={(idx) =>
                sendDisplaySection(this.state.song.title, idx)
              }
              clearBeamer={sendClearBeamer}
            />
          )}
          {this.state.display === "Beamer" && (
            <Beamer
              section={this.state.song.sections[this.state.section_idx]}
              title={this.state.song.title}
            />
          )}
        </div>
      </MuiThemeProvider>
    );
  }
}

export default App;
